#!/bin/sh 

# The torwuf service launcher

mkdir -p /var/run/torwuf-service/
chown www-torwuf:www-torwuf /var/run/torwuf-service/
sudo -u www-torwuf -g www-torwuf PYTHONPATH=${PYTHONPATH}:/usr/share/torwuf python3 /usr/share/torwuf/torwuf/
